<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="GastronomIQ.Application/GastronomIQ.Application.csproj" />
    <ProjectReference Include="GastronomIQ.Domain/GastronomIQ.Domain.csproj" />
    <ProjectReference Include="GastronomIQ.Infrastructure/GastronomIQ.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"
                      Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="GastronomIQ.Application/**/*.cs" />
    <Compile Remove="GastronomIQ.Application.Tests/**/*.cs" />
    <Compile Remove="GastronomIQ.Domain/**/*.cs" />
    <Compile Remove="GastronomIQ.Domain.Tests/**/*.cs" />
    <Compile Remove="GastronomIQ.Infrastructure/**/*.cs" />
    <Compile Remove="GastronomIQ.Integration.Tests/**/*.cs" />

    <None Remove="**/obj/**" />
    <None Remove="**/bin/**" />
    <Content Remove="**/obj/**" />
    <Content Remove="**/bin/**" />
  </ItemGroup>

</Project>
